name: Run Go Tests

on:
  push:
    branches: [ "main" , "test", "testbench"]
  pull_request:
    branches: [ "main", "test"," testbench"]

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run tests
        run: go test -run=^$ -bench . ./app/benchmarks/*trad_test.go
