name: Run Go Tests

on:
  push:
    branches: [ "main" , "testingbench", "testbench"]
  pull_request:
    branches: [ "main", "testingbench"," testbench"]

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: PFB Bench
        run: go test -v -tags=Tradbenchmarks -bench=. -run=^$ ./app/benchmarks/...
